services:
  # FastAPI Backend Service
  medrag-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: medrag-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./vector_store:/app/vector_store
      - ./cached_recordings:/app/cached_recordings
    networks:
      - medrag-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/query/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s

  # Streamlit Frontend Service
  medrag-frontend:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: medrag-frontend
    restart: unless-stopped
    ports:
      - "8501:8501"
    environment:
      - RAG_API_URL=http://medrag-backend:8000/api/v1/query/query
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    networks:
      - medrag-network
    depends_on:
      - medrag-backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  medrag-network:
    driver: bridge

volumes:
  cached_recordings:
    driver: local
  minio_data:
    driver: local
